---
apiVersion: v1
kind: Namespace
metadata:
  name: diskstatefulset
spec:
  finalizers:
  - kubernetes

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginxstatefulset
  namespace: diskstatefulset
spec:
  serviceName: "nginx"
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: www #annotation for velero Restic (filesystem backup): use volumename as value
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /mnt/azuredisk
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default 
      resources:
        requests:
          storage: 1Gi
